#!/usr/bin/bash
# ==============================================================================
# file       : bash_functions
# author     : daniel lee
# description: my bash functions
# ==============================================================================

# all-in-one extraction function
function extract {
    if [ -f $1 ]; then
        case $1 in
            *.tar    ) tar -xvf   $1;;
            *.tar.bz2) tar -jxvf  $1;;
            *.tbz2   ) tar -jxvf  $1;;
            *.tar.gz ) tar -zxvf  $1;;
            *.tgz    ) tar -zxvf  $1;;
            *.bz2    ) bunzip2    $1;;
            *.gz     ) gunzip     $1;;
            *.zip    ) unzip      $1;;
            *.Z      ) uncompress $1;;
            *.7z     ) 7z e       $1;;
            *        ) echo "'$1' cannot be extracted via extract()!";;
        esac
    else
        echo "'$1' is not a valid file!"
    fi
}
