#!/usr/bin/bash
# ==============================================================================
# file       : bash_profile
# author     : daniel lee
# description: my bash configuration file (run by login shell)
# ==============================================================================

# load my bash configuration
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
