#!/usr/bin/bash
# ==============================================================================
# file       : bashrc
# author     : daniel lee
# description: my bash configuration file (run by non-login shell)
# ==============================================================================

# load default bash configuration
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# load my bash aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# load my bash functions
if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

# load my work environment
if [ -f ~/.work_env.bash ]; then
    . ~/.work_env.bash
fi
